within ;
package ServoArm
  import SI = Modelica.Units.SI;

  model Plant
    "Open-loop plant: DC motor + ideal gearbox + vertical-plane arm with tip payload (MSL components only)"

    // ---- Electrical parameters (motor) ----
    parameter SI.Resistance R_a = 2.0 "Armature resistance";
    parameter SI.Inductance L_a = 1.0e-3 "Armature inductance";
    parameter SI.ElectricalTorqueConstant k_t = 0.05 "Torque/EMF constant (N.m/A = V.s/rad)";

    // ---- Mechanical drivetrain ----
    parameter SI.Inertia J_r = 5.0e-6 "Rotor inertia";
    parameter Real N = 50 "Gear ratio (flange_a.phi/flange_b.phi)";

    // ---- Arm body (from CAD/mass_properties.json) ----
    parameter SI.Mass m_arm = 0.2416428 "Arm mass";
    parameter SI.Position r_arm[3] = {0, -0.285, 0} "Pivot -> tip (frame_a to frame_b)";
    parameter SI.Position r_CM[3] = {0, -0.1357582, 0} "Pivot -> CoM";
    parameter SI.Inertia I_11 = 1.7996e-3 "Inertia about x (frame_a axes)";
    parameter SI.Inertia I_22 = 2.0233e-5 "Inertia about y (frame_a axes)";
    parameter SI.Inertia I_33 = 1.8158e-3 "Inertia about z (frame_a axes)";
    parameter SI.Inertia I_21 = 0 "Product of inertia";
    parameter SI.Inertia I_31 = 0 "Product of inertia";
    parameter SI.Inertia I_32 = 0 "Product of inertia";

    // ---- Payload ----
    parameter SI.Mass payload_m = 0.20 "Payload point mass";
    parameter SI.Position r_payload[3] = {0, -0.280, 0} "Pivot -> payload position";

    // ---- Interface ----
    Modelica.Blocks.Interfaces.RealInput v "Motor terminal voltage (V)"
      annotation (Placement(transformation(origin = {-24, -34}, extent = {{-220, -130}, {-180, -90}}),
        iconTransformation(extent = {{-220, -130}, {-180, -90}})));
    Modelica.Blocks.Interfaces.RealOutput phi "Arm angle (rad, 0 = down, + = toward horizontal)"
      annotation (Placement(transformation(origin = {-66, -56}, extent = {{180, 50}, {220, 90}}),
        iconTransformation(extent = {{180, 50}, {220, 90}})));
    Modelica.Blocks.Interfaces.RealOutput i "Motor current (A)"
      annotation (Placement(transformation(extent = {{180, -90}, {220, -50}}),
        iconTransformation(extent = {{180, -90}, {220, -50}})));

    // ---- MultiBody frame ----
    inner Modelica.Mechanics.MultiBody.World world
      annotation (Placement(transformation(extent = {{-200, 30}, {-180, 50}})));

    // ---- Pivot joint (MultiBody <-> Rotational bridge) ----
    Modelica.Mechanics.MultiBody.Joints.Revolute revolute(
      useAxisFlange = true,
      n = {0, 0, 1})
      annotation (Placement(transformation(extent = {{-160, 30}, {-140, 50}})));

    // ---- Arm body ----
    Modelica.Mechanics.MultiBody.Parts.BodyShape arm(
      r = r_arm,
      r_CM = r_CM,
      m = m_arm,
      I_11 = I_11,
      I_22 = I_22,
      I_33 = I_33,
      I_21 = I_21,
      I_31 = I_31,
      I_32 = I_32,
      animation = false)
      annotation (Placement(transformation(origin = {22, 0}, extent = {{-120, 30}, {-100, 50}})));

    // ---- Arm geometry from CAD (visual only; mass properties above) ----
    // Generated by openmodelica_cad_import_shape from CAD/Arm.stl:
    // pivot = hole centre at mid-thickness (15, 15, 5) mm, axes_map {x:-y, y:x, z:z}, mm -> m.
    Modelica.Mechanics.MultiBody.Visualizers.FixedShape armShape(
      shapeType = "modelica://ServoArm/Resources/Shapes/Arm.stl",
      r_shape = {0, 0, 0},
      lengthDirection = {1, 0, 0},
      widthDirection = {0, 1, 0},
      length = 1,
      width = 1,
      height = 1,
      color = {180, 180, 190})
      annotation (Placement(transformation(extent = {{-120, 80}, {-100, 100}})));

    // ---- Payload offset + mass ----
    // Anchored at the PIVOT node (revolute.frame_b), so r_payload is measured from the
    // pivot: payload sits at 280 mm from the pivot, 5 mm inboard of the 285 mm arm tip.
    Modelica.Mechanics.MultiBody.Parts.FixedTranslation payloadOffset(r = r_payload)
      annotation (Placement(transformation(origin = {42, 40}, extent = {{-120, 10}, {-100, 30}})));
    Modelica.Mechanics.MultiBody.Parts.PointMass payload(m = payload_m)
      annotation (Placement(transformation(origin = {68, 40}, extent = {{-80, 10}, {-60, 30}})));

    // ---- Drivetrain ----
    // Note: Revolute.support is grounded internally by the joint (unconditional internal
    // Fixed), and IdealGear(useSupport=false) is implicitly grounded, so no external
    // Fixed ground element is needed here.
    Modelica.Mechanics.Rotational.Components.IdealGear gear(ratio = N, useSupport = false)
      annotation (Placement(transformation(origin = {-22, 0}, extent = {{-100, -50}, {-80, -30}})));
    Modelica.Mechanics.Rotational.Components.Inertia rotorInertia(J = J_r)
      annotation (Placement(transformation(origin = {-18, 0}, extent = {{-40, -50}, {-20, -30}})));
    Modelica.Electrical.Analog.Basic.RotationalEMF emf(k = k_t, useSupport = false)
      annotation (Placement(transformation(origin = {-58, -52}, extent = {{20, -50}, {40, -30}})));

    // ---- Electrical circuit ----
    Modelica.Electrical.Analog.Sources.SignalVoltage voltageSource
      annotation (Placement(transformation(origin = {16, -50}, extent = {{-200, -130}, {-180, -110}})));
    Modelica.Electrical.Analog.Sensors.CurrentSensor currentSensor
      annotation (Placement(transformation(origin = {-6, 0}, extent = {{-160, -130}, {-140, -110}})));
    Modelica.Electrical.Analog.Basic.Resistor resistor(R = R_a)
      annotation (Placement(transformation(extent = {{-120, -130}, {-100, -110}})));
    Modelica.Electrical.Analog.Basic.Inductor inductor(L = L_a)
      annotation (Placement(transformation(extent = {{-80, -130}, {-60, -110}})));
    Modelica.Electrical.Analog.Basic.Ground ground
      annotation (Placement(transformation(origin = {2, -30}, extent = {{-150, -160}, {-130, -140}})));

  equation
    // Expose metrics
    phi = revolute.phi;
    connect(currentSensor.i, i) annotation (Line(points = {{-156, -131}, {40, -131}, {40, -70}, {200, -70}},
      color = {0, 0, 127}));

    // Electrical series: source -> current sensor -> R -> L -> emf, return via ground
    connect(voltageSource.p, currentSensor.p)
      annotation (Line(points = {{-184, -170}, {-193, -170}, {-193, -120}, {-166, -120}}, color = {0, 0, 255}));
    connect(currentSensor.n, resistor.p)
      annotation (Line(points = {{-146, -120}, {-120, -120}}, color = {0, 0, 255}));
    connect(resistor.n, inductor.p)
      annotation (Line(points = {{-100, -120}, {-80, -120}}, color = {0, 0, 255}));
    connect(inductor.n, emf.p)
      annotation (Line(points = {{-60, -120}, {-20, -120}, {-20, -82}, {-28, -82}},
        color = {0, 0, 255}));
    connect(voltageSource.n, ground.p)
      annotation (Line(points = {{-164, -170}, {-138, -170}},
        color = {0, 0, 255}));
    connect(emf.n, ground.p)
      annotation (Line(points = {{-28, -102}, {-28, -132}, {-138, -132}, {-138, -170}},
        color = {0, 0, 255}));

    // Drivetrain: emf -> rotor inertia -> gear -> revolute axis
    connect(emf.flange, rotorInertia.flange_a)
      annotation (Line(points = {{-18, -92}, {0, -92}, {0, -40}, {-58, -40}}));
    connect(rotorInertia.flange_b, gear.flange_a)
      annotation (Line(points = {{-38, -40}, {-122, -40}}));
    connect(gear.flange_b, revolute.axis)
      annotation (Line(points = {{-102, -40}, {-150, -40}, {-150, 30}}));

    // MultiBody chain: world -> revolute -> arm (tip at frame_b)
    connect(world.frame_b, revolute.frame_a)
      annotation (Line(points = {{-180, 40}, {-160, 40}}, color = {95, 95, 95}, thickness = 0.5));
    connect(revolute.frame_b, arm.frame_a)
      annotation (Line(points = {{-140, 40}, {-98, 40}}, color = {95, 95, 95}, thickness = 0.5));
    connect(revolute.frame_b, armShape.frame_a)
      annotation (Line(points = {{-140, 40}, {-130, 40}, {-130, 90}, {-120, 90}}, color = {95, 95, 95}, thickness = 0.5));
    // Payload anchored at the PIVOT node (revolute.frame_b), not the arm tip
    connect(revolute.frame_b, payloadOffset.frame_a)
      annotation (Line(points = {{-140, 40}, {-140, 60}, {-78, 60}}, color = {95, 95, 95}, thickness = 0.5));
    connect(payloadOffset.frame_b, payload.frame_a)
      annotation (Line(points = {{-58, 60}, {-2, 60}}, color = {95, 95, 95}, thickness = 0.5));

    // Drive voltage input
    connect(v, voltageSource.v)
      annotation (Line(points = {{-224, -144}, {-203, -144}, {-203, -158}, {-174, -158}}, color = {0, 0, 127}));
    annotation (Icon(coordinateSystem(extent = {{-200, -160}, {200, 160}})),
      Diagram(coordinateSystem(extent = {{-220, -180}, {220, 160}})));
  end Plant;

  model SmokeTest "Plant driven by a 5 V step at t = 0"
    ServoArm.Plant plant
      annotation (Placement(transformation(extent = {{-40, -20}, {40, 20}})));
    Modelica.Blocks.Sources.Step step(
      height = 5,
      startTime = 0)
      annotation (Placement(transformation(extent = {{-100, -10}, {-80, 10}})));
  equation
    connect(step.y, plant.v)
      annotation (Line(points = {{-79, 0}, {-40, 0}}, color = {0, 0, 127}));
    annotation (Icon(coordinateSystem(extent = {{-100, -100}, {100, 100}})),
      Diagram(coordinateSystem(extent = {{-140, -100}, {100, 100}})),
      experiment(StopTime = 4));
  end SmokeTest;

  annotation (uses(Modelica(version = "4.1.0")));
end ServoArm;
